/*
Tipos de datos en C
Elaboró: MARH
21.10.20021
*/

#include <stdio.h>
#include <conio.h>

main(){
	
	//VARIABLES:
	char a; //CARACTER (8BITS = 1BYTE), COMPARAR CON EL HOLA MUNDO, AQUÍ SÓLO SE GUARDA UN CARACTER Y NO UNA CADENA
	int b; //ENTEROS (32BITS = 4BYTES), EL ÚLTIMO INDICA SIGNO DEL NÚMERO: 0=+ Y 1=-
	float c; //FLOTANTE, SISTEMA NUMÉRICO DE PUNTO FLOTANTE DE SIMPLE PRECISIÓN, SE NORMALIZAN LOS NÚMEROS (32BITS = 4BYTES)
	double d; //DOBLE SISTEMA NUMÉRICO DE PUNTO FLOTANTE DE DOBLE PRECISIÓN (64BITS = 8BYTES)
	
	b=2147483647;
	printf ("%d",b); //LOS "%" SE USAN COMO COMODÍN PARA INDICAR QUÉ ESTAMOS PONIENDO, EN ESTE CASO, UN ENTERO
	b=b+1; //EN LA TERMINAL ESTO MOSTRARÁ UN SIGNO NEGATIVO, DEBIDO A QUE CAMBIA TODO EL BINARIO, INCLUYENDO EL ÚLTIMO BIT, EL DEL SIGNO
	printf("\t%d",b);
	
	a='w'; //UN SIMPLE CARACTER SE DECLARA ENTRE COMILLAS SIMPLES
	printf("\n%c",a); //"#c" COMODÍN PARA CARACTERES
	printf("\t%d",a); //"%d" EN CARACTERES DA SU VALOR EN ASCII
	getch();
}
